version: "3.9"
services:
  cli:
    build: cli
    volumes:
      - ..:/workspaces/laravel

  fpm:
    build: fpm
    volumes:
      - ..:/workspaces/laravel
    user: 1000:1000

  nginx:
    build: nginx
    volumes:
      - ..:/workspaces/laravel
    ports:
      - 8689:80
    depends_on:
      - fpm

  # postgres:
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_DB: laravel
  #     POSTGRES_USER: root
  #     POSTGRES_HOST_AUTH_METHOD: trust
  mariadb:
    image: mariadb:10.4
    expose:
      # Expose mariadb port to php service (Access as hostname "mariadb" from within php container)
      - "3306"
    # Uncomment to allow access to mariadb from external tools
    # ports:
    #     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DBres1pr0m!
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: siraprom2

  redis:
    image: redis:6.2-alpine
    expose:
      - "6379"

